package com.wuqy.dao.mapper;

import com.wuqy.common.entity.db.T1;
import com.wuqy.common.entity.db.T1Example;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface T1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    int countByExample(T1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    int deleteByExample(T1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    int insert(T1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    int insertSelective(T1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    List<T1> selectByExample(T1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") T1 record, @Param("example") T1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    int updateByExample(@Param("record") T1 record, @Param("example") T1Example example);
}