package com.wuqy.common.entity.db;

import lombok.Builder;

@Builder
public class T1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.id
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.id
     *
     * @return the value of t1.id
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.id
     *
     * @param id the value for t1.id
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T1 other = (T1) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbggenerated Tue Dec 15 17:21:38 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}