spring:
  profiles:
    active: ##{spring.profiles.active}##
    #include: common
  task:
    scheduling:
      pool:
        size: 16
  main:
    allow-bean-definition-overriding: true
  http-client:
    pool:
      maxTotalConnect: 1000
      maxConnectPerRoute: 200
      connectTimeout: 5000
      readTimeout: 10000
      connectionRequestTimout: 200
      retryTimes: 0
      charset: UTF-8
      keepAliveTime: 10
  servlet:
    multipart:
      max-file-size: 1100MB
      max-request-size: 1100MB
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/db3?serverTimezone=Asia/Shanghai
    username: root
    password:
    mybatis:
      configuration:
        map-underscore-to-camel-case: true
      mapper-locations: classpath*:mysql/db/mapper/*.xml
  second-datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3316/db3?serverTimezone=Asia/Shanghai
    username: root
    password:
    mybatis:
      configuration:
        map-underscore-to-camel-case: true
      mapper-locations: classpath*:mysql/db/mapper/*.xml
server:
  port: 8010
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:logback-spring.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 插件配置 pagehelper
pagehelper:
  helperDialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: false
  # 支持通过 Mapper 接口参数来传递分页参数
  supportMethodsArguments: true

project:
  datasource:
    db1:
      url: jdbc:mysql://127.0.0.1:3306/db3?serverTimezone=Asia/Shanghai
      username: root
      password:
      name: db3
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      configuration:
        maximum-pool-size: 200
        connection-test-query: select 1
        minimum-idle: 20
      mybatis:
        configuration:
          map-underscore-to-camel-case: true
        mapper-locations: classpath*:mysql/db/mapper/*.xml
    db2:
      url: jdbc:mysql://127.0.0.1:3316/db3?serverTimezone=Asia/Shanghai
      username: root
      password:
      name: db3
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      configuration:
        maximum-pool-size: 200
        connection-test-query: select 1
        minimum-idle: 20
      mybatis:
        configuration:
          map-underscore-to-camel-case: true
        mapper-locations: classpath*:mysql/db/mapper/*.xml
environment: dev
hmily:
  tcc :
    serializer : kryo
    recoverDelayTime : 128
    retryMax : 3
    scheduledDelay : 128
    scheduledThreadMax :  10
    repositorySupport : db
    tccDbConfig :
      driverClassName  : com.mysql.jdbc.Driver
      url :  jdbc:mysql://127.0.0.1:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
      username : root
      password : root

        #repositorySupport : redis
        #tccRedisConfig:
                 #masterName: mymaster
                 #sentinel : true
                 #sentinelUrl : 192.168.1.91:26379;192.168.1.92:26379;192.168.1.93:26379
                 #password  : foobaredbbexONE123


       # repositorySupport : zookeeper
       #         host      : 92.168.1.73:2181
       #         sessionTimeOut      :  100000
       #         rootPath  : /tcc

       # repositorySupport : mongodb
       #       mongoDbUrl  : 192.168.1.68:27017
       #       mongoDbName  :  happylife
       #       mongoUserName  : xiaoyu
       #       mongoUserPwd   : 123456

       # repositorySupport : file
       #         path      : /account
       #         prefix    :  account